### ISSUE TITLE
Interesting Plugin Error with Chef 13

### ISSUE THREAD

**Issue by kylegoch** [chef-cookbooks/ohai#67]
### Cookbook version
5.0.3

### Chef-client version
13.0.118 (also 13.1.5)

### Platform Details
Ubuntu 16.04

### Scenario:
Use Packer to make an AMI with a Chef-Solo provisioner.

### Steps to Reproduce:
We can only produce the error on our Jenkins server. 
Running the same Packer job locally (OSX) does not produce the issue.

### Expected Result:
Ohai cookbook to load

### Actual Result:
```
[0;32m    amazon-ebs: [2017-04-25T18:26:02+00:00] WARN: [DEPRECATION] Plugin at /tmp/packer-chef-solo/ohai/cookbook_plugins/ohai/matchers.rb is a version 6 plugin. Version 6 plugins will not be supported in future releases of Ohai. Please upgrade your plugin to version 7 plugin syntax. For more information visit here: docs.chef.io/ohai_custom.html[0m
[0;32m    amazon-ebs:[0m
[0;32m    amazon-ebs: Running handlers:[0m
[0;32m    amazon-ebs: [2017-04-25T18:26:02+00:00] ERROR: Running exception handlers[0m
[0;32m    amazon-ebs: Running handlers complete[0m
[0;32m    amazon-ebs: [2017-04-25T18:26:02+00:00] ERROR: Exception handlers complete[0m
[0;32m    amazon-ebs: Chef Client failed. 0 resources updated in 03 seconds[0m
[0;32m    amazon-ebs: [2017-04-25T18:26:02+00:00] FATAL: Stacktrace dumped to /tmp/packer-chef-solo/local-mode-cache/cache/chef-stacktrace.out[0m
[0;32m    amazon-ebs: [2017-04-25T18:26:02+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report[0m
[0;32m    amazon-ebs: [2017-04-25T18:26:02+00:00] ERROR: wrong number of arguments (given 1, expected 3)[0m
[0;32m    amazon-ebs: [2017-04-25T18:26:02+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)[0m
```

So we use Packer to build amis. We switched to Chef 13 and tested locally (Macbook), and were able to build an ami in AWS with out issue. So we tried to run the same Packer command on our Jenkins server and get the output above.

Note though, that output is being reported by the AWS instance that Packer is provisioning, not Jenkins itself.

We can work around this issue by using Chef 12.19.x. We only get this error on Chef 13 and only when our Jenkins runs Packer.

Both locally and Jenkins run Chef-DK 1.3.43 and Packer 1.0.0. They also use the same Berksfile as well.

So far the only error we have to go on is the above Ohai cookbook error.

**Comment by kylegoch** [comment]
Here is the chef stacktrace too
```
Generated at 2017-04-25 19:06:14 +0000
ArgumentError: wrong number of arguments (given 1, expected 3)
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.0.0/lib/ohai/dsl/plugin/versionvi.rb:27:in `initialize'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.0.0/lib/ohai/loader.rb:223:in `new'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.0.0/lib/ohai/loader.rb:223:in `load_v7_plugin'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.0.0/lib/ohai/loader.rb:93:in `block in load_additional'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.0.0/lib/ohai/loader.rb:90:in `collect'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.0.0/lib/ohai/loader.rb:90:in `load_additional'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.0.0/lib/ohai/system.rb:116:in `run_additional_plugins'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/run_context/cookbook_compiler.rb:119:in `compile_ohai_plugins'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/run_context/cookbook_compiler.rb:73:in `compile'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/run_context.rb:187:in `load'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/policy_builder/expand_node_object.rb:97:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/client.rb:513:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/client.rb:281:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/application.rb:291:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/application.rb:279:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/application.rb:279:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/application.rb:244:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/application.rb:232:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/application/solo.rb:225:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/bin/chef-solo:25:in `<top (required)>'
/usr/bin/chef-solo:58:in `load'
/usr/bin/chef-solo:58:in `<main>'
```

**Comment by iennae** [comment]
where does your /tmp/packer-chef-solo/ohai/cookbook_plugins/ohai/matchers.rb come from?

**Comment by kylegoch** [comment]
Not actually sure. We dont have a custom one we are adding or anything though.

But again, the hilarious issue is I can run the same set of commands with Packer and Chef 13 on my Mac and have no issues or errors.

**Comment by kylegoch** [comment]
It looks like `/tmp/packer-chef-solo/ohai/cookbook_plugins/ohai/matchers.rb` actually matches this https://github.com/chef-cookbooks/ohai/blob/master/libraries/matchers.rb

But we dont do anything with the ohai cookbook. It just gets pulled in as a dependency.

**Comment by kylegoch** [comment]
Also, this is still happening on 5.1.0 of this cookbook and Chef 13.1.31.

Here is the chef-stacktrace.out
```
Generated at 2017-05-31 19:50:03 +0000
ArgumentError: wrong number of arguments (given 1, expected 3)
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.1.0/lib/ohai/dsl/plugin/versionvi.rb:27:in `initialize'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.1.0/lib/ohai/loader.rb:223:in `new'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.1.0/lib/ohai/loader.rb:223:in `load_v7_plugin'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.1.0/lib/ohai/loader.rb:93:in `block in load_additional'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.1.0/lib/ohai/loader.rb:90:in `collect'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.1.0/lib/ohai/loader.rb:90:in `load_additional'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.1.0/lib/ohai/system.rb:116:in `run_additional_plugins'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/run_context/cookbook_compiler.rb:119:in `compile_ohai_plugins'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/run_context/cookbook_compiler.rb:73:in `compile'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/run_context.rb:192:in `load'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/policy_builder/expand_node_object.rb:97:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/client.rb:513:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/client.rb:281:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application.rb:291:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application.rb:279:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application.rb:279:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application.rb:244:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application.rb:232:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:58:in `load'
/usr/bin/chef-client:58:in `<main>'
```

**Comment by kylegoch** [comment]
Found the issue. Something had tainted the Berkshelf. Clearing it out completely solved this issue.

**Comment by iennae** [comment]
Thanks for updating with the solution!

**Comment by rhoegg** [comment]
What was tainted in Berkshelf, and how would I go about untainting it? :)

**Comment by iennae** [comment]
@rhoegg remove the Berksfile.lock.

**Comment by kylegoch** [comment]
@rhoegg I actually had to clear out the literal `.berkshelf` folder stored in the profile of the user on our Jenkins server.
