### ISSUE TITLE
spec_helper.rb 

### ISSUE THREAD

**Issue by chris-carr-bose** [chef-cookbooks/ohai#76]
### Cookbook version
5.2.5

### Chef-client version
14.7.17
Chef Development Kit Version: 3.6.17
chef-client version: 14.7.17
delivery version: master (19553a3799e2b1ebee5f7f5798ddb74fd61603f8)
berks version: 7.0.7
kitchen version: 1.23.3
inspec version: 3.0.61

### Platform Details
MacOS X Mojave 10.13.2

### Scenario:
My unit tests fail due to deprecation warning related plugin_helper.rb

### Steps to Reproduce:
1. rm -Rf ~/.chef/ohai
2. chef generate cookbook reduction
3. cd reduction
4. echo "depends 'nginx'" >> metadata.rb
5. berks install
6. echo "include_recipe 'nginx::source'" > recipes/default.rb
7. chef exec rspec # See Actual Result :: rspec
8. ls ~/.chef/ohai/cookbook_plugins/ohai/ # <-- written by ohai cookbook?
9. ohai # works fine
10. ohai -d ~/.chef/ohai/cookbook_plugins # See Actual Result :: ohai

### Expected Result:
Generated spec tests should return 'converges successfully'.

#### rspec
```
F/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/ohai-14.8.10/lib/ohai/plugins/windows/filesystem.rb:26: warning: already initialized constant CONVERSION_STATUS
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/ohai-14.8.10/lib/ohai/plugins/windows/filesystem.rb:26: warning: previous definition of CONVERSION_STATUS was here
F

Failures:

  1) reduction::default When all attributes are default, on Ubuntu 16.04 converges successfully
     Failure/Error: expect { chef_run }.to_not raise_error
     
       expected no Exception, got #<Ohai::Exceptions::IllegalPluginDefinition: [DEPRECATION] Plugin at /Users/redacted/.chef/ohai/cookbo...o be updated to the v7 Ohai plugin format. See https://docs.chef.io/ohai_custom.html for v7 syntax.> with backtrace:
         # ./spec/unit/recipes/default_spec.rb:15:in `block (3 levels) in <top (required)>'
         # ./spec/unit/recipes/default_spec.rb:19:in `block (4 levels) in <top (required)>'
         # ./spec/unit/recipes/default_spec.rb:19:in `block (3 levels) in <top (required)>'
     # ./spec/unit/recipes/default_spec.rb:19:in `block (3 levels) in <top (required)>'

[second test showed same trace]

Finished in 4.48 seconds (files took 2.44 seconds to load)
2 examples, 2 failures

Failed examples:

rspec ./spec/unit/recipes/default_spec.rb:18 # reduction::default When all attributes are default, on Ubuntu 16.04 converges successfully
rspec ./spec/unit/recipes/default_spec.rb:31 # reduction::default When all attributes are default, on CentOS 7.4.1708 converges successfully
```

#### ohai
```
$ ohai -d ~/.chef/ohai/cookbook_plugins
[2018-12-25T07:43:14-05:00] INFO: The plugin path /etc/chef/ohai/plugins does not exist. Skipping...
Traceback (most recent call last):
	12: from /usr/local/bin/ohai:296:in `<main>'
	11: from /usr/local/bin/ohai:296:in `load'
	10: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/ohai-14.8.10/bin/ohai:26:in `<top (required)>'
	 9: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/ohai-14.8.10/lib/ohai/application.rb:80:in `run'
	 8: from /opt/chefdk/embedded/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
	 7: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/ohai-14.8.10/lib/ohai/application.rb:82:in `block in run'
	 6: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/ohai-14.8.10/lib/ohai/application.rb:111:in `run_application'
	 5: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/ohai-14.8.10/lib/ohai/system.rb:93:in `all_plugins'
	 4: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/ohai-14.8.10/lib/ohai/system.rb:100:in `load_plugins'
	 3: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/ohai-14.8.10/lib/ohai/loader.rb:78:in `load_all'
	 2: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/ohai-14.8.10/lib/ohai/loader.rb:78:in `each'
	 1: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/ohai-14.8.10/lib/ohai/loader.rb:79:in `block in load_all'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/ohai-14.8.10/lib/ohai/loader.rb:133:in `load_plugin_class': [DEPRECATION] Plugin at /Users/redacted/.chef/ohai/cookbook_plugins/ohai/plugin_helpers.rb is a version 6 plugin. Version 6 plugins are no longer supported by Ohai. This plugin will need to be updated to the v7 Ohai plugin format. See https://docs.chef.io/ohai_custom.html for v7 syntax. (Ohai::Exceptions::IllegalPluginDefinition)
```

**Comment by chris-carr-bose** [comment]
Here's a better reduction that does not rely on the nginx cookbook:
```bash
rm -Rf ~/.chef/ohai
chef generate cookbook reduction
cd reduction
echo "depends 'ohai'" >>metadata.rb
berks install
echo "ohai_plugin 'reduction_plugin'" >>recipes/default.rb
mkdir -p files/default
cat <<EOH >files/default/reduction_plugin.rb
> Ohai.plugin(:Reduction) do
>   provides 'reduction'
>   collect_data(:default) do
>     attribute 'reduction'
>   end
> end
> EOH
chef exec rspec                        # tests fail as above
ohai                                   # succeeds as above
ohai -d ~/.chef/ohai/cookbook_plugins  # fails as above
```

**Comment by chris-carr-bose** [comment]
I can no longer reproduce this with chef-client 14.13.11.
